/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MAIN;

/**
 *
 * @author Mwk Ams
 */
public class SCORES extends javax.swing.JFrame {

    /**
     * Creates new form SCORES
     */
    public SCORES() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        score1 = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        score3 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SCORES");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setText("GEOFFREY");
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 200, 30));

        name2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        name2.setForeground(new java.awt.Color(255, 255, 255));
        name2.setText("BOSCO");
        getContentPane().add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 210, 30));

        name3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        name3.setForeground(new java.awt.Color(255, 255, 255));
        name3.setText("BENJAMIN");
        getContentPane().add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 210, 30));

        score1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        score1.setForeground(new java.awt.Color(204, 0, 0));
        score1.setText("1010");
        getContentPane().add(score1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 80, 30));

        score2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        score2.setForeground(new java.awt.Color(204, 0, 0));
        score2.setText("900");
        getContentPane().add(score2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 70, 30));

        score3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        score3.setForeground(new java.awt.Color(204, 0, 0));
        score3.setText("700");
        getContentPane().add(score3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 70, 30));

        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 100, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MAIN/scores.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SCORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SCORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SCORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SCORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SCORES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel close;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel score2;
    private javax.swing.JLabel score3;
    // End of variables declaration//GEN-END:variables
}
